name: Peter Pedersen
favicon: null
layout_spectrum: 0.9169456916861236
typography_spectrum: 0.5020185010507703
title: UK IT Leadership Council
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#5e6b72'
    - '#ff0000'
    - '#ffcd00'
    - '#de5255'
  brandStrength: 0.6875
  lightness: 0.625
  saturation: 0.8125
  rhythmicContrast: 0.5
purpose: []
