name: Peter Pedersen
favicon: null
layout_spectrum: 0.9169456916861236
typography_spectrum: 0.5020185010507703
title: UK IT Leadership Council
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.5675759646110237
  lightness: 0.35161085869185627
  saturation: 0.6533787325024605
  rhythmicContrast: 0.28730926290154457
purpose: []
